# Generated by Django 2.2.10 on 2020-06-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
